package com.diamondxe.Beans

data class SearchGemstoneTypeModel(
    var stock_id:String,
    var item_name:String,
    var category:String,
    var supplier_id:String,
    var cut_grade:String,
    var certificate_name:String,
    var certificate_no:String,
    var stock_no:String,
    var growth_type:String,
    var polish:String,
    var symmetry:String,
    var measurement:String,
    var fluorescence_intensity:String,
    var carat:String,
    var dia_wt:String,
    var color:String,
    var clarity:String,
    var shape:String,
    var shade:String,
    var table_perc:String,
    var depth_perc:String,
    var luster:String,
    var eye_clean:String,
    var treatment:String,
    var inscription:String,
    var diamond_image:String,
    var diamond_video:String,
    var discount:String,
    var total_gst_perc:String,
    var subtotal:String,
    var total_price:String,
    var is_returnable:String,
    var dxe_prefered:String,
    var status:String,
    var is_available_for_sale:String,
    var is_cart:String,
    var is_wishlist:String,
    var on_hold:String,
    var tax:String,
    var price_per_ct:String,
    var shipping_charge:String,
    var platform_fee_amt:String,
    var dxe_markup:String,
    var coupon_discount_perc:Double,
    var subtotal_after_coupon_discount:String,
    var currencySymbol:String,
    var showingSubTotal:String,
    var setVisible:Boolean


)